# Generated by Django 5.2.8 on 2025-11-23 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavioral_purpose_tag', models.CharField(max_length=150)),
                ('minimum_investment', models.CharField(max_length=100)),
                ('eligibility', models.TextField()),
                ('integration_type', models.CharField(max_length=255)),
                ('digital_verification_availability', models.CharField(max_length=120)),
                ('official_url', models.URLField()),
                ('ufhs_tag', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['behavioral_purpose_tag', 'minimum_investment', 'official_url'],
            },
        ),
        migrations.CreateModel(
            name='BankingFinancialAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_bank_account', models.BooleanField(default=False)),
                ('type_of_account', models.CharField(blank=True, max_length=50, null=True)),
                ('has_upi_wallet', models.BooleanField(default=False)),
                ('avg_monthly_bank_balance', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_txn_per_month', models.IntegerField(blank=True, null=True)),
                ('has_credit_card_bnpl', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BehavioralPsychometric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_monthly_savings_goals', models.BooleanField(default=False)),
                ('track_expenses', models.BooleanField(default=False)),
                ('extra_income_behaviour', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_miss_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('digital_comfort_level', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behavior', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditLiabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existing_loans', models.BooleanField(default=False)),
                ('type_of_loan', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_emi', models.IntegerField(blank=True, null=True)),
                ('missed_payments_6m', models.BooleanField(default=False)),
                ('informal_borrowing', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpensesObligations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_per_month', models.IntegerField(blank=True, null=True)),
                ('utilities_expense', models.IntegerField(blank=True, null=True)),
                ('education_medical_expense', models.IntegerField(blank=True, null=True)),
                ('avg_household_spend', models.IntegerField(blank=True, null=True)),
                ('dependents_expense', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentSchemeEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_aadhaar', models.BooleanField(default=False)),
                ('has_pan', models.BooleanField(default=False)),
                ('enrolled_in_scheme', models.BooleanField(default=False)),
                ('scheme_names', models.CharField(blank=True, max_length=300, null=True)),
                ('monthly_govt_benefit', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='govt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_income_source', models.CharField(blank=True, max_length=200, null=True)),
                ('monthly_income_range', models.CharField(blank=True, max_length=50, null=True)),
                ('working_days_per_month', models.IntegerField(blank=True, null=True)),
                ('income_variability', models.CharField(blank=True, max_length=50, null=True)),
                ('mode_of_payment', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='income', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDemographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city_district', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation_type', models.CharField(blank=True, max_length=100, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=50, null=True)),
                ('children', models.CharField(blank=True, max_length=50, null=True)),
                ('dependents', models.IntegerField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular_savings_habit', models.BooleanField(default=False)),
                ('savings_amount_per_month', models.CharField(blank=True, max_length=50, null=True)),
                ('has_insurance', models.CharField(blank=True, max_length=200, null=True)),
                ('type_of_insurance', models.CharField(blank=True, max_length=50, null=True)),
                ('has_pension_pf', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UHFSScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uhfs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFinancialLiteracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modules_completed', models.IntegerField(default=0)),
                ('average_quiz_score', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
