# Generated by Django 5.2.8 on 2025-11-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_alter_userfinancialliteracy_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="purpose",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="scheme_description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
