# Generated by Django 5.2.8 on 2025-11-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_product_name_product_purpose_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
