# Generated by Django 5.2.8 on 2025-11-30 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_productpurchase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uhfsscore',
            name='components',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='uhfsscore',
            name='composite',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uhfsscore',
            name='domain_risk',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='uhfsscore',
            name='overall_risk',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.CharField(blank=True, choices=[('personal_demographic', 'Personal Demographic'), ('income_employment', 'Income & Employment'), ('banking_financial_access', 'Banking & Financial Access'), ('credit_liabilities', 'Credit & Liabilities'), ('savings_insurance', 'Savings & Insurance'), ('expenses_obligations', 'Expenses & Obligations'), ('behavioral_psychometric', 'Behavioral & Psychometric'), ('government_scheme_eligibility', 'Government Scheme Eligibility'), ('user_financial_literacy', 'User Financial Literacy')], max_length=50, null=True)),
                ('completed_step', models.CharField(blank=True, choices=[('personal_demographic', 'Personal Demographic'), ('income_employment', 'Income & Employment'), ('banking_financial_access', 'Banking & Financial Access'), ('credit_liabilities', 'Credit & Liabilities'), ('savings_insurance', 'Savings & Insurance'), ('expenses_obligations', 'Expenses & Obligations'), ('behavioral_psychometric', 'Behavioral & Psychometric'), ('government_scheme_eligibility', 'Government Scheme Eligibility'), ('user_financial_literacy', 'User Financial Literacy')], max_length=50, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
