# Generated by Django 5.2.8 on 2025-11-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_uhfsscore_components_uhfsscore_composite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='behavioral_purpose_tag',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='digital_verification_availability',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='eligibility',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='integration_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_investment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='official_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
