# Generated by Django 5.2.8 on 2025-12-01 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_alter_product_behavioral_purpose_tag_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="productpurchase",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="productpurchase",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="productpurchase",
            name="id_proof",
            field=models.FileField(blank=True, null=True, upload_to="kyc/id_proofs/"),
        ),
        migrations.AlterField(
            model_name="productpurchase",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="productpurchase",
            name="status",
            field=models.CharField(
                choices=[
                    ("INITIATED", "Initiated"),
                    ("PENDING", "Pending"),
                    ("OTP_VERIFIED", "OTP Verified"),
                    ("KYC_IN_PROGRESS", "KYC In Progress"),
                    ("IN_REVIEW", "In Review"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("COMPLETED", "Completed"),
                    ("SUCCESS", "Success"),
                    ("FAILURE", "Failure"),
                ],
                default="INITIATED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productpurchase",
            name="video_verification",
            field=models.FileField(blank=True, null=True, upload_to="kyc/videos/"),
        ),
        migrations.CreateModel(
            name="UserProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "policy_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("purchase_date", models.DateTimeField()),
                (
                    "premium_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "premium_frequency",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("HALF_YEARLY", "Half-Yearly"),
                            ("YEARLY", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("next_premium_due", models.DateField()),
                ("tenure_years", models.PositiveIntegerField(blank=True, null=True)),
                ("maturity_date", models.DateField(blank=True, null=True)),
                ("auto_renew", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("ACTIVE", "Active"),
                            ("LAPSED", "Lapsed"),
                            ("CANCELLED", "Cancelled"),
                            ("MATURED", "Matured"),
                        ],
                        default="INITIATED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_products",
                        to="finance.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPremiumPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "premium_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("premium_date", models.DateField()),
                ("paid_on", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                        ],
                        default="INITIATED",
                        max_length=10,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="premium_payments",
                        to="finance.userproduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("PREMIUM_REMINDER", "Premium Reminder"),
                            ("PREMIUM_OVERDUE", "Premium Overdue"),
                            ("MATURITY_REMINDER", "Maturity Reminder"),
                            ("KYC_REMINDER", "KYC Reminder"),
                            ("GENERAL", "General Message"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("scheduled_for", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.userproduct",
                    ),
                ),
            ],
        ),
    ]
