# Generated by Django 5.2.8 on 2025-12-01 04:02

import finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_alter_productpurchase_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productpurchase",
            name="address_proof",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=finance.models.get_address_proof_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="productpurchase",
            name="id_proof",
            field=models.FileField(
                blank=True, null=True, upload_to=finance.models.get_id_proof_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="productpurchase",
            name="video_verification",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=finance.models.get_video_verification_upload_path,
            ),
        ),
    ]
