# Generated by Django 5.2.8 on 2025-12-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_alter_productpurchase_address_proof_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="details",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of the product and its benefits",
                null=True,
            ),
        ),
    ]
