# Generated by Django 5.2.8 on 2025-12-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0010_product_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk_category",
                    models.CharField(
                        choices=[
                            ("Income Stability", "Income Stability"),
                            ("Financial Behavior", "Financial Behavior"),
                            ("Reliability & Tenure", "Reliability & Tenure"),
                            ("Protection Readiness", "Protection Readiness"),
                        ],
                        db_index=True,
                        max_length=100,
                    ),
                ),
                (
                    "risk_trigger",
                    models.CharField(
                        help_text="Description of the risk trigger condition",
                        max_length=500,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("🔴 High", "🔴 High"),
                            ("🟠 Medium", "🟠 Medium"),
                            ("🟢 Low", "🟢 Low"),
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "recommended_instruments",
                    models.TextField(
                        help_text="Comma-separated list of recommended product names"
                    ),
                ),
                (
                    "behavioral_tag",
                    models.CharField(
                        help_text="Behavioral tag for categorization", max_length=200
                    ),
                ),
                (
                    "intro_section",
                    models.TextField(
                        help_text="Introductory text to display in the app"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order within same risk category and level",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["risk_category", "risk_level", "order"],
                "indexes": [
                    models.Index(
                        fields=["risk_category", "risk_level"],
                        name="finance_ris_risk_ca_44c8c7_idx",
                    )
                ],
                "unique_together": {("risk_category", "risk_trigger", "risk_level")},
            },
        ),
    ]
