# Generated by Django 5.2.8 on 2025-12-04 15:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0011_riskrecommendation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="behavioralpsychometric",
            name="user",
        ),
        migrations.RemoveField(
            model_name="creditliabilities",
            name="user",
        ),
        migrations.RemoveField(
            model_name="expensesobligations",
            name="user",
        ),
        migrations.RemoveField(
            model_name="governmentschemeeligibility",
            name="user",
        ),
        migrations.RemoveField(
            model_name="savingsinsurance",
            name="user",
        ),
        migrations.RemoveField(
            model_name="incomeemployment",
            name="income_variability",
        ),
        migrations.RemoveField(
            model_name="incomeemployment",
            name="mode_of_payment",
        ),
        migrations.RemoveField(
            model_name="incomeemployment",
            name="monthly_income_range",
        ),
        migrations.RemoveField(
            model_name="incomeemployment",
            name="working_days_per_month",
        ),
        migrations.AddField(
            model_name="incomeemployment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="incomeemployment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="personaldemographic",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personaldemographic",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userfinancialliteracy",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userfinancialliteracy",
            name="literacy_score",
            field=models.FloatField(
                blank=True,
                help_text="Calculated score (0-1) based on modules and quiz scores",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userfinancialliteracy",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="incomeemployment",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="income_employment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="onboardingprogress",
            name="completed_step",
            field=models.CharField(
                blank=True,
                choices=[
                    ("personal_demographic", "Personal & Demographic (Q1-10)"),
                    ("income_employment", "Income & Employment (Q11)"),
                    ("income_stability", "Income Stability (Q12-15)"),
                    ("financial_behavior", "Financial Behavior (Q16-19)"),
                    ("reliability_tenure", "Reliability & Tenure (Q20-23)"),
                    ("protection_readiness", "Protection Readiness (Q24-27)"),
                    ("financial_literacy", "Financial Literacy (Q28)"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="onboardingprogress",
            name="current_step",
            field=models.CharField(
                blank=True,
                choices=[
                    ("personal_demographic", "Personal & Demographic (Q1-10)"),
                    ("income_employment", "Income & Employment (Q11)"),
                    ("income_stability", "Income Stability (Q12-15)"),
                    ("financial_behavior", "Financial Behavior (Q16-19)"),
                    ("reliability_tenure", "Reliability & Tenure (Q20-23)"),
                    ("protection_readiness", "Protection Readiness (Q24-27)"),
                    ("financial_literacy", "Financial Literacy (Q28)"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personaldemographic",
            name="children",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No"), ("Daughter", "Daughter")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personaldemographic",
            name="education_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("None", "None"),
                    ("School", "School"),
                    ("College", "College"),
                    ("Graduate", "Graduate"),
                    ("Other", "Other"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personaldemographic",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personaldemographic",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Married", "Married"),
                    ("Single", "Single"),
                    ("Other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personaldemographic",
            name="occupation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Gig worker", "Gig worker"),
                    ("Small retailer", "Small retailer"),
                    ("Farmer", "Farmer"),
                    ("Other", "Other"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personaldemographic",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_demographic",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userfinancialliteracy",
            name="average_quiz_score",
            field=models.FloatField(
                default=0.0, help_text="Average quiz score (0-100)"
            ),
        ),
        migrations.CreateModel(
            name="FinancialBehavior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monthly_savings",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Less than ₹500", "Less than ₹500"),
                            ("₹500–₹1,000", "₹500–₹1,000"),
                            ("₹1,000–₹3,000", "₹1,000–₹3,000"),
                            ("More than ₹3,000", "More than ₹3,000"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "saving_methods",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of saving method choices",
                        null=True,
                    ),
                ),
                (
                    "missed_payments",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("Not applicable", "Not applicable"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "bill_payment_timeliness",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Always", "Always"),
                            ("Mostly", "Mostly"),
                            ("Sometimes", "Sometimes"),
                            ("Rarely", "Rarely"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "score_a",
                    models.FloatField(blank=True, help_text="Q16 score", null=True),
                ),
                (
                    "score_b",
                    models.FloatField(blank=True, help_text="Q17 score", null=True),
                ),
                (
                    "score_c",
                    models.FloatField(blank=True, help_text="Q18 score", null=True),
                ),
                (
                    "score_d",
                    models.FloatField(blank=True, help_text="Q19 score", null=True),
                ),
                (
                    "subcategory_score",
                    models.FloatField(
                        blank=True, help_text="Weighted subcategory score", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_behavior",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IncomeStability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monthly_income",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("₹5,000–10,000", "₹5,000–10,000"),
                            ("₹10,001–20,000", "₹10,001–20,000"),
                            ("₹20,001–30,000", "₹20,001–30,000"),
                            ("₹30,001–50,000", "₹30,001–50,000"),
                            ("₹50,000+", "₹50,000+"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "income_drop_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Never", "Never"),
                            ("Once", "Once"),
                            ("Often", "Often"),
                            ("Almost every month", "Almost every month"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "working_days_per_week",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1–2 days", "1–2 days"),
                            ("3–4 days", "3–4 days"),
                            ("5–6 days", "5–6 days"),
                            ("Every day", "Every day"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "income_trend",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Increased", "Increased"),
                            ("Stable", "Stable"),
                            ("Decreased", "Decreased"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "score_a",
                    models.FloatField(blank=True, help_text="Q12 score", null=True),
                ),
                (
                    "score_b",
                    models.FloatField(blank=True, help_text="Q13 score", null=True),
                ),
                (
                    "score_c",
                    models.FloatField(blank=True, help_text="Q14 score", null=True),
                ),
                (
                    "score_d",
                    models.FloatField(blank=True, help_text="Q15 score", null=True),
                ),
                (
                    "subcategory_score",
                    models.FloatField(
                        blank=True, help_text="Weighted subcategory score", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="income_stability",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProtectionReadiness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "has_health_insurance",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("Not sure", "Not sure"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "has_accident_life_insurance",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("Not sure", "Not sure"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "emergency_expense_handling",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Immediately", "Immediately"),
                            ("Within 1 week", "Within 1 week"),
                            ("Within 1 month", "Within 1 month"),
                            ("Cannot manage", "Cannot manage"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "current_savings_fund",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("₹0–500", "₹0–500"),
                            ("₹501–1,000", "₹501–1,000"),
                            ("₹1,001–5,000", "₹1,001–5,000"),
                            ("₹5,000+", "₹5,000+"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "score_a",
                    models.FloatField(blank=True, help_text="Q24 score", null=True),
                ),
                (
                    "score_b",
                    models.FloatField(blank=True, help_text="Q25 score", null=True),
                ),
                (
                    "score_c",
                    models.FloatField(blank=True, help_text="Q26 score", null=True),
                ),
                (
                    "score_d",
                    models.FloatField(blank=True, help_text="Q27 score", null=True),
                ),
                (
                    "subcategory_score",
                    models.FloatField(
                        blank=True, help_text="Weighted subcategory score", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protection_readiness",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReliabilityTenure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform_tenure",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Less than 3 months", "Less than 3 months"),
                            ("3–6 months", "3–6 months"),
                            ("6–12 months", "6–12 months"),
                            ("More than 1 year", "More than 1 year"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "active_days_per_week",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1–2", "1–2"),
                            ("3–4", "3–4"),
                            ("5–6", "5–6"),
                            ("7 days", "7 days"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "cancellation_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Rarely", "Rarely"),
                            ("Sometimes", "Sometimes"),
                            ("Often", "Often"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "customer_rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "1 star"),
                            ("2", "2 stars"),
                            ("3", "3 stars"),
                            ("4", "4 stars"),
                            ("5", "5 stars"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "score_a",
                    models.FloatField(blank=True, help_text="Q20 score", null=True),
                ),
                (
                    "score_b",
                    models.FloatField(blank=True, help_text="Q21 score", null=True),
                ),
                (
                    "score_c",
                    models.FloatField(blank=True, help_text="Q22 score", null=True),
                ),
                (
                    "score_d",
                    models.FloatField(blank=True, help_text="Q23 score", null=True),
                ),
                (
                    "subcategory_score",
                    models.FloatField(
                        blank=True, help_text="Weighted subcategory score", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reliability_tenure",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="BankingFinancialAccess",
        ),
        migrations.DeleteModel(
            name="BehavioralPsychometric",
        ),
        migrations.DeleteModel(
            name="CreditLiabilities",
        ),
        migrations.DeleteModel(
            name="ExpensesObligations",
        ),
        migrations.DeleteModel(
            name="GovernmentSchemeEligibility",
        ),
        migrations.DeleteModel(
            name="SavingsInsurance",
        ),
    ]
