# Generated by Django 5.2.8 on 2025-12-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingsection",
            name="audio_url",
            field=models.URLField(blank=True, help_text="Audio content URL", null=True),
        ),
        migrations.AlterField(
            model_name="trainingsection",
            name="content_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("text", "Text"),
                    ("mixed", "Mixed"),
                ],
                help_text="Primary content type (optional). Use 'mixed' if section has multiple types.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="trainingsection",
            name="text_content",
            field=models.TextField(blank=True, help_text="Text content", null=True),
        ),
        migrations.AlterField(
            model_name="trainingsection",
            name="video_url",
            field=models.URLField(blank=True, help_text="Video content URL", null=True),
        ),
    ]
