# Generated by Django 5.2.8 on 2025-12-01 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0002_alter_trainingsection_audio_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingquestion",
            name="training",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="training.trainingsection",
            ),
        ),
    ]
